### PR TITLE
[bugfix] windows incompatibilty

### PR DESCRIPTION
**Pull request by SylTi**
Currently running 'truffle test' or any other truffle cmd on windows open the truffle.js file. Renaming it solve that issue.

### CODE REVIEW

**Comment by frangio** [comment]
Thanks for contributing @SylTi!

Do you know if there are other issues besides this with regards to Windows compatibility?

**Comment by Neurone** [comment]
This is not releated to Windows in general: if you use **Power Shell or other terminals** (i.e. the one integrated into Visual Studio Code) the problem does not appear. It happens with **`cmd.exe`** because the command line takes into consideration the `PATHEXT` enviroment variable.

For example, a common `PATHEXT` value at system level is:

`PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`

This tells Windows to consider files with those extensions as executables. When you run the `truffle ` command inside your project folder, _truffle.js_ takes the precedence and it _starts_. This means that, if you assigned for example a default text editor to .js file, when you type `truffle` inside the project folder the truffle.js file is opened inside the default text editor.

To get rid of this particular problem, you can override the default PATHEXT system environment variable with a user environment variable, removing the .JS extension from the admitted values.

IMHO it's better to use a _safer_ `PATHEXT` in any case. For example, I use this:

`PATHEXT=.COM;.EXE;.BAT;.CMD;.MSC`

**Comment by SylTi** [comment]
@frangio obviously the script to run the test/coverage etc are not working. they could be migrated to an npm script instead.
@Neurone cmd is still the default on windows. For example, PhpStorm uses it. 
You might be right to change that env var, but I think OpenZeppelin should work out of the box.

**Comment by frangio** [comment]
Yes I agree that the change is harmless enough that we can merge it.

**Comment by frangio** [comment]
Actually, the change broke the coverage analysis. I'm going to have to revert it and reopen untl sc-forks/solidity-coverage#93 is fixed.

**Pull request merged**
