### PR TITLE
Create tests for MultisigWallet

### PR DESCRIPTION
**Pull request by adklempner**

### CODE REVIEW

**Comment by maraoz** [comment]
4 tests failing, can you check if it's related to: https://github.com/OpenZeppelin/zeppelin-solidity/pull/106/files ?

**Comment by Qkyrie** [comment]
It is, adding a **payable** modifier to MultisigWalletMock should probably already resolve some of your issues

**Comment by maraoz** [comment]
please rebase or squash (lots of unwanted commits in the PR)

**Comment by maraoz** [comment]
ACK

**Pull request merged**
