### PR TITLE
remove timer test helper

### PR DESCRIPTION
**Pull request by maraoz**
fixes https://github.com/OpenZeppelin/zeppelin-solidity/issues/252

### CODE REVIEW

**Comment by frangio** [comment]
We have to helpers that do the same thing. The other one is [`increaseTime`](https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/test/helpers/increaseTime.js). We should remove `timer`, I think.

**Comment by maraoz** [comment]
PR repurposed to remove it :)

**Comment by frangio** [comment]
Nice!

**Comment by frangio** [comment]
Nice! Let's also remove the now unused `day` variable.

**Pull request merged**
