### PR TITLE
docs: fix contributing link

### PR DESCRIPTION
**Pull request by elopio**
- [x] 📘 I've reviewed the [OpenZeppelin Contributor Guidelines](../blob/master/CONTRIBUTING.md)
- [x] ✅ I've added tests where applicable to test my new functionality.
- [x] 📖 I've made sure that my contracts are well-documented.
- [x] 🎨 I've run the JS/Solidity linters and fixed any issues (`npm run lint:all:fix`).

### CODE REVIEW

**Comment by Shrugs** [comment]
nice catch! I think the full path should actually be something like `../blob/master/CONTRIBUTING.md` so it resolves correctly? I've edited your description to be that syntax and it seems happy. 

Can you update the PR?

**Comment by elopio** [comment]
woah, you are right. Updated, thanks @Shrugs.

**Comment by Shrugs** [comment]
travis is being flaky. will merge this when it's happy

**Comment by Shrugs** [comment]
thanks @elopio !!

**Pull request merged**
