### PR TITLE
Add coveralls

### PR DESCRIPTION
**Pull request by maraoz**
Fixes https://github.com/OpenZeppelin/zeppelin-solidity/issues/230

### CODE REVIEW

**Comment by maraoz** [comment]
It worked!!!

**Comment by cgewecke** [comment]
👍  Great!!!!

**Comment by maraoz** [comment]
This is all based on your work @cgewecke, thanks! :)

**Comment by cgewecke** [comment]
Oh no thanks for putting it in @maraoz! It's an honor.

**Comment by federicobond** [comment]
Love this! Kudos to @cgewecke. Now let's get that number as high as we can! 🚀

**Pull request merged**
