### PR TITLE
Bounty with factory (merged) version

### PR DESCRIPTION
**Pull request by makoto**
Hi guys. I had all sorts of issue rebasing from upstream so created a new branch and merged upstream instead.

Please review @gleim @maraoz @adklempner @demibrener 

### Changes

- [x] Make claim logic generic by calling `checkInvariant` of external contract.
- [x] Remove hard coding target contract in Bounty by calling `deployContract` of factory contract.
- [x] Pass factory contract address when creating Bounty contract
- [x] Add `kill` capability
- [x] Add documentation on `README`

### Tests

```
Contract: Bounty
  ✓ creates bounty contract with factory address (123ms)
  ✓ sets reward (438ms)
  ✓ cannot create bounty without address
  ✓ empties itself when killed (694ms)
  Against secure contract
    ✓ checkInvariant returns true (196ms)
    ✓ cannot claim reward (696ms)
  Against broken contract
    ✓ checkInvariant returns false (147ms)
    ✓ claims reward (706ms)
```
### Open discussion

- Are there any good ways to raise error if the given factory does not implement `checkInvariant` function?
- Currently it is very difficult for researchers to break the invariants as they have no special privileges. Should we allow Factory to take researcher's address so that contract owner can (optionally) allow researcher to become the owner of the copy contract?

### CODE REVIEW

**Comment by maraoz** [comment]
4 tests failing on this branch, please fix
screenshot from 2016-10-28 16-55-43

**Comment by makoto** [comment]
@maraoz Interesting. That error does not happen in my environment. The error indicates that you could not deploy mock contract.

Can you add `  console.log('network', deployer.network)` into your `2_deploy_contracts.js` then run `truffle test` to make sure that it's running under `test` environment?

```
module.exports = function(deployer) {
  deployer.deploy(PullPaymentBid);
  deployer.deploy(BadArrayUse);
  deployer.deploy(ProofOfExistence);
  deployer.deploy(Ownable);
  deployer.deploy(LimitFunds);
  console.log('network', deployer.network)
  if(deployer.network == 'test'){
    deployer.deploy(SecureTargetFactory);
    deployer.deploy(InsecureTargetFactory);
  };
};
```

**Comment by makoto** [comment]
@maraoz fixed. Try again. The reason it was failing was that it was not deploying `SecureTargetMock` and `InsecureTargetMock` factory in the migration file.

**Comment by maraoz** [comment]
Fixed => ACK 
I think I prefer tests to use `SomeContract.new()` than `SomeContract.deployed()`, but we can fix that later, and I'm not sure about it.

**Pull request merged**
