### PR TITLE
Use the latest ERC-721 draft interface, fixes #745

### LINKED ISSUE #745: Use #841 reference implementation in OpenZeppelin
Presently, OpenZeppelin has ERC-721 (draft) implemented here https://github.com/OpenZeppelin/zeppelin-solidity/tree/master/contracts/token/ERC721

A reference implementation has just been released and added to the standard (draft). The reference is here: https://github.com/nastassiasachs/ERC721ExampleDeed

Could the reference implementation please be added to OpenZeppelin.

Also, please note, we prefer the name DEED, currently it is listed as a TOKEN. We would appreciate that for consistency a new DEED folder could be created.

Ping @nastassiasachs

### PR DESCRIPTION
**Pull request by fulldecent**
Fixes #745 

# 🚀 Description

The ERC-721 is near finalization. I have included the latest interfaces into here.

We are now working on interop testing and would love to work with the OpenZeppelin project on this.

- [x] 📘 I've reviewed the [OpenZeppelin Contributor Guidelines](/docs/CONTRIBUTING.md)
- [ ] ✅ I've added tests where applicable to test my new functionality.
- [x] 📖 I've made sure that my contracts are well-documented. HELL YES
- [ ] 🎨 I've run the JS/Solidity linters and fixed any issues (`npm run lint:all:fix`).

### CODE REVIEW

**Comment by fulldecent** [comment]
Quoting @spalladino from https://gitter.im/ETH-NFT/Lobby to move the discussion here.

> For minor discussion on OpenZeppelin/zeppelin-solidity#777, would you rather keep the discussion here, or on the PR itself? For instance, I'd consider changing visibility of external methods to public (as in ERC20), or remove seemingly unnecessary payable modifiers.

**Comment by fulldecent** [comment]
I have made these requested changes.

Just wanted to note here that it is okay that OpenZeppelin's interface for ERC-721 is different than the canonical ERC-721 (external -> public, no payable). And it does not mean that the standard is deficient. The standard recognizes and makes allowance for this already.

Specifically, the standard is correct for the long term, future versions of Solidity. And this file in OZ is correct today.

Citing https://github.com/fulldecent/EIPs/blob/patch-2/EIPS/eip-721.md#caveats:

* https://github.com/ethereum/solidity/issues/2330
  * Current versions of Solidity allow using `public` in an interface and disallow using external in an interface with public in a contract.
  * Future Solidity requires `external` in interfaces and allows contracts with `public` to implement those functions.
* https://github.com/ethereum/solidity/issues/3412:
   * Current versions of Solidity require a `payable` interface to be implemented by a `payable` contract function. 
   * Future versions of Solidity will allow a `payable` interface to be implemented by a default non-payable contract function. 

I'm pointing this out to assert that the standard does regulate on the payability and non-payability of functions. And I continue to fight to make the Solidity `interface` grammar more expressive!

**Comment by spalladino** [comment]
Thanks @fulldecent! I'll compare this interface with the candidate implementation from @facuspagnuolo at https://github.com/OpenZeppelin/zeppelin-solidity/pull/682, rework the implementation as needed, and revert back here if there is any strong mismatch.

**Comment by spalladino** [comment]
Closing in favour of https://github.com/OpenZeppelin/zeppelin-solidity/pull/803. Note that this interface was included in that PR. Again, thanks for your work @fulldecent!

**Pull request closed without merging**
