### PR TITLE
Make token transfer extensible in crowdsale

### PR DESCRIPTION
**Pull request by thesved**
Add a dedicated tokenTransfer internal function, which can be used to create flexible token transfer mechanisms, like:
- pull pattern: during crowdsale there is no minting, which reduces gas costs during a high congestion period, and make it possible to withdraw tokens after finalization
- trust fund like crowdsale: it doesn't mint but transfers its own tokens, when tokens are premined

### CODE REVIEW

**Comment by SylTi** [comment]
https://github.com/OpenZeppelin/zeppelin-solidity/pull/426

**Comment by frangio** [comment]
Thanks a lot @thesved! This is useful.

Can you please add [NatSpec](https://github.com/ethereum/wiki/wiki/Ethereum-Natural-Specification-Format) documentation to the new function? We can merge afterwards.

I'm not sure that `transferToken` is the best name, because some of the use cases like the pull pattern are not exactly transfers. What other possible names can we think of?

**Comment by frangio** [comment]
Also, since the idea is to enable usage of `Crowdsale` without `MintableToken` and minting, something needs to be done about the `createTokenContract` function.

**Comment by ajsantander** [comment]
@thesved any updates on the tweaks frangio suggested?

**Comment by ajsantander** [comment]
@thesved 
Thanks for your suggestion. We've taken your idea and incorporated it in a general refactor of crowdsales.
If you're interested in following progress, please see #744.

**Pull request closed without merging**
