### PR TITLE
Make rate function extensible in crowdsale

### LINKED ISSUE #302: Crowdsale token price rate is fixed
Users should be able to customize the price function for Crowdsale contracts.

### PR DESCRIPTION
**Pull request by thesved**
Create a getRate function, which can be used to implement a flexible rate function, like giving bonus for early contributors or whitelist addresses.

Fixes #302.

### CODE REVIEW

**Comment by SylTi** [comment]
https://github.com/OpenZeppelin/zeppelin-solidity/pull/426

**Comment by grimsa** [comment]
#632 is a better solution IMO

**Comment by Shrugs** [comment]
#632 has been moved to https://github.com/OpenZeppelin/zeppelin-solidity/pull/638

but agreed that #638 is more flexible

**Comment by frangio** [comment]
Superceded by #638.

**Pull request closed without merging**
