### PR TITLE
Renamed files and replaced occurencies of 'Stoppable' to 'Pausable'

### PR DESCRIPTION
**Pull request by JGcarv**
Renamed all occurrences of 'Stopabble' to 'Pausable' as requested on issue #6.

I ran all the tests and all of them passed.

Let me know if there's another step I need to make to close this issue.

Thanks!  

captura de tela 2017-02-01 as 21 35 42

### CODE REVIEW

**Comment by adklempner** [comment]
LGTM

**Comment by federicobond** [comment]
LGTM. Nitpick: should the public variable be called `paused` now?

**Comment by federicobond** [comment]
It's weird that git did not recognize the test file as renamed.

**Comment by JGcarv** [comment]
@federicobond Hmm great point. I must admit that I didn't read the source code that carefully. I'll make this change and also check the test file.

**Comment by maraoz** [comment]
LGTM. Thanks @federicobond for reviewing!

**Pull request merged**
