### PR TITLE
 Small gas improvement in SafeMath.sol

### PR DESCRIPTION
**Pull request by Janther**
# 🚀 Description

Although this is nothing major, by not allocating memory to an extra variable, some gas can be saved in this (overall used) library.

I kept the original code in comments for devs to read what the original safety checks were and why they were removed.

Originally the `div` functions had 2 safety checks.

```Solidity
/**
 * @dev Integer division of two numbers, truncating the quotient.
 */
function div(uint256 a, uint256 b) internal pure returns (uint256) {
    assert(b > 0);
    uint256 c = a / b;
    assert(a == b * c + a % b);
    return c;
}
```

It was improved by removing the checks because they were not needed.

```Solidity
/**
 * @dev Integer division of two numbers, truncating the quotient.
 */
function div(uint256 a, uint256 b) internal pure returns (uint256) {
    // assert(b > 0); // Solidity automatically throws when dividing by 0
    uint256 c = a / b;
    // assert(a == b * c + a % b); // There is no case in which this doesn't hold
    return c;
}
```

This was good so far but the `c` variable is not needed anymore.

```Solidity
/**
 * @dev Integer division of two numbers, truncating the quotient.
 */
function div(uint256 a, uint256 b) internal pure returns (uint256) {
    // assert(b > 0); // Solidity automatically throws when dividing by 0
    // uint256 c = a / b;
    // assert(a == b * c + a % b); // There is no case in which this doesn't hold
    return a / b;
}
```

- [x] 📘 I've reviewed the [OpenZeppelin Contributor Guidelines](/docs/CONTRIBUTING.md)
- [x] ✅ I've added tests where applicable to test my new functionality.
- [x] 📖 I've made sure that my contracts are well-documented.
- [x] 🎨 I've run the JS/Solidity linters and fixed any issues (`npm run lint:all:fix`).

### CODE REVIEW

**Comment by Shrugs** [comment]
neat catch! Did you profile the two options? You'd think that whole thing would be inlined or something and it wouldn't matter 😅 

I'd profile it myself by my remix is being a little odd for me today. It's definitely missing the `DUP1 			uint256 c` opcode in the new version, so I support it.

**Comment by Janther** [comment]
I performed both options in two scenarios in kovan.:

  1) Initiating a variable:
    - With `c` gas used `42373`.
https://kovan.etherscan.io/tx/0xc48ee763cca288ec28c5aa7c7f98efebe79a516da19176c9e947427bd9aba613

    - Without `c` gas used `42360`.
https://kovan.etherscan.io/tx/0xa3ecaccdfc536b0badded50a2fe70493185c0f4fb68d27ffb1d3052006ebdd2a

  2) Changing an initiated variable:
    - With `c` gas used `27693`.
https://kovan.etherscan.io/tx/0x1509a3cc6e2db4be03cbaf1ac3244b3d0df6b5a32bf3594ddff5583240e666a2

    - Without `c` gas used `27680`.
https://kovan.etherscan.io/tx/0xf8852fd3e68512d48758f2c975e97f67a41d2beaaaf890bf81edca51ee6b0f90

In both scenarios, the library not using `c` uses 13 gas less.

**Comment by facuspagnuolo** [comment]
Thanks @Janther ! 
I tried this contract in remix

```sol
library SafeMath {
    function div1(uint256 a, uint256 b) internal pure returns (uint256) {
        return a / b;
    }
  
    function div2(uint256 a, uint256 b) internal pure returns (uint256) {
        uint256 c = a / b;
        return c;
    }
}

contract UsingSafeMath {
    function div1(uint256 a, uint256 b) public pure returns (uint256) {
        return SafeMath.div1(a,b);
    }
  
    function div2(uint256 a, uint256 b) public pure returns (uint256) {
        return SafeMath.div2(a,b);
    }
}
```

and got the following output:

image

As you can see I'm getting that `div2` costs less gas than `div1`, am I right?

**Comment by Shrugs** [comment]
image

I got the same result! That's really bizarre. latest compiler with optimizations on. 

I also changed the code to look like

```
pragma solidity ^0.4.18;

library SafeMath {
    function div1(uint256 a, uint256 b) internal pure returns (uint256) {
        return a / b;
    }
}

library SafeMath2 {
    function div2(uint256 a, uint256 b) internal pure returns (uint256) {
        uint256 c = a / b;
        return c;
    }
}

contract UsingSafeMath {
    function div1(uint256 a, uint256 b) public pure returns (uint256) {
        return SafeMath.div1(a,b);
    }
}

contract UsingSafeMath2 {
    function div2(uint256 a, uint256 b) public pure returns (uint256) {
        return SafeMath2.div2(a,b);
    }
}
```

and got a similarly confusing, but less obvious gas difference:

image

image

**Comment by facuspagnuolo** [comment]
Closing then, thanks @Janther !

**Comment by Janther** [comment]
Using the same code provided by you:

```Solidity
pragma solidity ^0.4.18;

library SafeMath {
    function div1(uint256 a, uint256 b) internal pure returns (uint256) {
        return a / b;
    }
}

library SafeMath2 {
    function div2(uint256 a, uint256 b) internal pure returns (uint256) {
        uint256 c = a / b;
        return c;
    }
}

contract UsingSafeMath {
    function div1(uint256 a, uint256 b) public pure returns (uint256) {
        return SafeMath.div1(a,b);
    }
}

contract UsingSafeMath2 {
    function div2(uint256 a, uint256 b) public pure returns (uint256) {
        return SafeMath2.div2(a,b);
    }
}
```
screenshot 2018-03-23 14 57 35
screenshot 2018-03-23 14 57 54

`div1` (without `c`) uses 13 gas less than `div2` (with `c`).

I used the latest compiler `0.4.21`.

**Comment by Janther** [comment]
By enabling optimization the difference is much lower.

screenshot 2018-03-28 11 19 21
screenshot 2018-03-28 11 19 39

Only 5 gas but `div1` (without `c`) is still the cheaper one.

**Comment by frangio** [comment]
I think the results observed by @facuspagnuolo were tainted by the additional gas cost of the function dispatching, because `div2` was defined after `div1` in the same contract.

The changed code by @Shrugs better assesses the gas costs of each independently.

**Comment by facuspagnuolo** [comment]
Good catch guys 🎉

**Pull request merged**
