### PR TITLE
Consistent spellings of reentrant

### PR DESCRIPTION
**Pull request by nemild**
Changed `rentrancy_lock` variable to `reentrancy_lock`

### CODE REVIEW

**Comment by Shrugs** [comment]
Can you also change the `rentrancy` comment on L4?

**Comment by nemild** [comment]
@Shrugs Done

**Comment by nemild** [comment]
@Shrugs Should be good to go, but ping if I can make any other changes

**Comment by Shrugs** [comment]
LGTM, but I don't have merge abilities. @frangio?

**Comment by frangio** [comment]
Thanks @nemild and @Shrugs!

**Pull request merged**
