### PR TITLE
replace all instances of uint with uint256

### PR DESCRIPTION
**Pull request by morrme**
fixes: #226

### CODE REVIEW

**Comment by maraoz** [comment]
@morrme can you please rebase the branch so we can merge? Thanks!

**Comment by morrme** [comment]
I had trouble rebasing (very new to this operation).....any advice? Should I resolve the conflicts manually?

**Comment by maraoz** [comment]
Could you revert the contract changes and just leave the doc changes, so I can merge?

**Comment by DavidKnott** [comment]
@morrme @maraoz I think this PR can be closed given that an equivalent PR has already been merged

**Pull request closed without merging**
