### PR TITLE
Add bounties folder and CrowdsaleToken bounty contract

### PR DESCRIPTION
**Pull request by gleim**
Segregate bounty contracts, add CrowdsaleTokenBounty contract

### CODE REVIEW

**Comment by maraoz** [comment]
LGTM, but tests fail because of broken import paths in `CrowdsaleTokenBounty.sol`. Please make sure you run `truffle test` and that it works, which helps catch errors like these.
We should also probably make the Bounty contracts more generic, instead of having a separate file for each contract. I've opened this issue: https://github.com/OpenZeppelin/zeppelin-solidity/issues/32

**Comment by maraoz** [comment]
Tests fixed, ACK

**Comment by gleim** [comment]
Resolved.

**Comment by gleim** [comment]
Will do.  Also, interested to hear how we can balance more generic bounty
contracts with bounty contracts that exercise the specifics of detailed
contracts.

Bill

**Comment by maraoz** [comment]
@gleim This pull request by @makoto_inoue is working towards that. Check it out and comment your thoughts! https://github.com/OpenZeppelin/zeppelin-solidity/pull/35#issuecomment-256167926

**Pull request merged**
