### PR TITLE
Explicit public visibility on methods

### PR DESCRIPTION
**Pull request by dmx374**
Best practice for lisibility.

### CODE REVIEW

**Comment by SylTi** [comment]
I agree with you.
There is a bunch of files where they are missing.
Maybe it's better to update all of them in a single commit?

**Comment by dmx374** [comment]
I take care of it, count on me.

Envoyé de mon iPhone

**Comment by SylTi** [comment]
nice!
https://github.com/SylTi/zeppelin-solidity/commit/0646676bd5ebc71b63b9df09615ecbac9ee238fa 
Already did the RefundVault there. 
Very nice to see a french compatriot :D

**Comment by dmx374** [comment]
Here we go:
https://github.com/OpenZeppelin/zeppelin-solidity/pull/456

;-)

**Comment by frangio** [comment]
Closing in favor of #456.

**Pull request closed without merging**
