### PR TITLE
fix: make SplitPayment payable by default

### PR DESCRIPTION
**Pull request by Shrugs**
via [https://openzeppelin.slack.com/archives/C229D43PG/p1511519211000052](Slack)

cc @frangio

### CODE REVIEW

**Comment by frangio** [comment]
@abarmat Was there any reason the contract wasn't made `payable` by default? Do you see any problems with merging this?

**Comment by Shrugs** [comment]
Requiring the user to decide what is payable could be considered a feature... but I expect the vast majority of users will just want anything sent to the contract at deploy time and over the course of its existence to be split. 

Q: I assume that if I inherit this contract and then don't make my constructor payable, then the `SplitPayment`'s payable modifier doesn't do anything?

**Comment by abarmat** [comment]
Indeed it was a choice to leave the decision about how to receive payments to the user implementing the contract. Maybe the contract is a destination for selfdestruct() and is not payable by default or the payable function is a different one. Maybe there could be a SimpleSplitPayment which by default is payable. What are your thoughts?

**Comment by Shrugs** [comment]
I assume most people will want a simple splittable place to dump ether (my use case, to split the funds of a crowdsale to the correct addresses).

Undoing the payable modifiers is easier than adding them, since the people undoing them will be inheriting from SplitPayment regardless. It is something they'd have to be aware of, though.

**Pull request merged**
