### PR TITLE
Check transfer destination is not a zero address

### PR DESCRIPTION
**Pull request by pash7ka**

### CODE REVIEW

**Comment by pash7ka** [comment]
This is a fix for issue #400 (re-comitted)

**Comment by diegomart2000** [comment]
I think it is a good practice to also include test specs to verify new conditions. It also helps to measure the impact of a future change. What is the policy in here for tests?

**Comment by frangio** [comment]
You're correct @diegomart2000, we require tests for all features. @pash7ka can you add tests to see that transfers to `0x0` are rejected?

Can you also please remove the irrelevant commits in the branch? You can do it with an interactive rebase: `git rebase -i HEAD~6`.

**Comment by pash7ka** [comment]
I'll add tests and resubmit everuthing from scratch.

**Comment by frangio** [comment]
You don't need to create a new PR! You can rebase and force push (`git push -f`). 🙂

Thanks for your work though!

**Comment by pash7ka** [comment]
Sorry, I don't understand what I have to do with all this commits now.
I've tried `git rebase -i HEAD~6` and `git push -f` and it seems just created more mess..
My current brunch https://github.com/pash7ka/zeppelin-solidity/tree/issue-400 contains correct files and tests.

**Comment by frangio** [comment]
Don't worry, I'll merge the commits manually. (You will remain the author.)

**Comment by pash7ka** [comment]
Thank you!

**Pull request closed without merging**
