### PR TITLE
Update BasicToken.js

### PR DESCRIPTION
**Pull request by ProphetDaniel**
Improved code for same result.

### CODE REVIEW

**Comment by DavidKnott** [comment]
@ProphetDaniel Great refactor!  Could you please rebase it?

**Comment by ProphetDaniel** [comment]
@DavidKnott done!

**Comment by DavidKnott** [comment]
@ProphetDaniel Thanks a lot!

**Comment by maraoz** [comment]
Please rebase with master

**Comment by ProphetDaniel** [comment]
@maraoz , done!

**Comment by maraoz** [comment]
Please rebase following this guide: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by ajsantander** [comment]
@ProphetDaniel any updates on this? It would be great to wrap this up.

**Comment by ProphetDaniel** [comment]
Closed due to another refactor that made this one unnecessary.

**Pull request closed without merging**
