### PR TITLE
Shareable: improved code to styling conventions, added functionality todo with owners

### PR DESCRIPTION
**Pull request by RFVenter**

### CODE REVIEW

**Comment by frangio** [comment]
Thanks @RFVenter! We have been thinking about refactoring the Shareable contract. I have a couple questions.

Shareable is used in other parts of OpenZeppelin (only MultisigWallet for now) and these changes are breaking those uses. In particular the change in the constructor. I think in practice a Shareable contract always has a set of many owners, even at construction time, which is why they were constructor parameters. What did you consider ugly about them?

Have you thought about using a dynamic array to hold the owners?

**Comment by RFVenter** [comment]
Hi @frangio. Good job for a very diplomatic response 👍 Please excuse my crude comments (from before).

- The refactored names should be fine.
- I believe you Shareable should follow the same example as Owneable. Even Owneable has a builtin function to change the one single owner. Shareable should allow functionality to:
    - add owners
    - remove owners
    - change required amount of owners required for valid tx
 - Adding parameters to a constructor (especially an inherited one) is cumbersome. Why not simply give the creator of the contract sole ownership to be begin with, and then he/she can add owners later.

**Comment by maraoz** [comment]
@RFVenter can you please check broken tests?

**Comment by frangio** [comment]
Closed since `Shareable` has been removed in #328.

**Pull request closed without merging**
