### PR TITLE
Create Vault.sol

### PR DESCRIPTION
**Pull request by GriffGreen**
See the latest progress on this contract at https://github.com/Giveth/vaultcontract/blob/develop/contracts/

### CODE REVIEW

**Comment by maraoz** [comment]
Thanks for the contribution @GriffGreen! We've [wanted a Vault contract for some time now](https://github.com/OpenZeppelin/zeppelin-solidity/issues/21) :)

First comment I have is: Can we change license to MIT, as the rest of the OpenZeppelin codebase?

**Comment by GriffGreen** [comment]
Sorry i didnt see this for a while...

We strongly prefer the GPL license, especially at this stage, if people find ways to improve this code, and want to distribute it, we want it to be open source. 

However I do not consider myself an expert on this issue, I could be convinced otherwise with compelling arguments.

**Comment by misteraverin** [comment]
@GriffGreen  @maraoz yes, we can include GPL code in MIT
http://stackoverflow.com/a/5610965

**Comment by maraoz** [comment]
@misteraverin Did you read the whole answer? See this comment "Although you clarify later in your answer, it is very misleading to start off by saying that "you can" include GPL-licensed code in a MIT-licensed project. A project that was originally MIT-licensed can no longer be distributed as a whole under the MIT license once it contains code that is only available under GPL"

**Comment by maraoz** [comment]
@GriffGreen MIT is also open source. The problem with GPL is that it forces anyone using the code to be GPL, so closed-source projects wouldn't be able to use OpenZeppelin. We'll stick to MIT, so I'll ask you to change it here before merging.

**Comment by maraoz** [comment]
ping @GriffGreen

**Comment by AugustoL** [comment]
I like the contract, but it should use the Ownable contract form zeppelin as import and the tests for the contracts are missing too. @GriffGreen do yo want some help?

**Comment by ajsantander** [comment]
@AugustoL did this lead to a PR?

**Comment by ajsantander** [comment]
Closing an older issue this one deprecates. Might have useful info -> #21

**Comment by AugustoL** [comment]
Wow this is super outdated, @ajsantander Im going to take the lead on this and submit and implementation later, having a Vault contract will be super useful.

**Comment by frangio** [comment]
Closing this as the code is licensed under GPL and we won't be able to merge it.

Let's continue discussion in #21.

**Comment by GriffGreen** [comment]
@frangio  @maraoz Is there an absolute rule about no GPL code? We have some cool contracts that we would be excited about adding to the repo. I even have a guy (@quazia) who is excited to start importing all our code and our tests from github.com/Giveth over here... but we are content with the GPL license. 

No chance you could have a couple GPL repos?

**Comment by frangio** [comment]
We would love to work together on that, but afaict if we merge GPL code into OpenZeppelin the GPL license itself imposes the absolute rule that OpenZeppelin must then be GPL as well.

As a workaround, keeping the contracts in a different repo and available as a different package might work.

**Comment by GriffGreen** [comment]
Interesting. I see that it is clearly true that if a project mixes the code, they must GPL license every thing, but in the repo, it gets grey... 

I totally understand being cautious. 

Can we create an `openZ-external` repo and throw some of our code in there?

**Pull request closed without merging**
