### PR TITLE
resolve conflict between Ownable and ERC20 token.

### LINKED ISSUE #109: transfer method conflicts on using contract ERC20 Token and Ownable.
If you create a contract as an extension of an ERC20 Token contract and Ownable contract the transfer method will have conflicts because is used in both contracts with different purpose.

can be solved changing name transfer method on Ownable to transferOwnership.

### PR DESCRIPTION
**Pull request by Qkyrie**
fixes  #109 

- changed ownable transfer function name to transferOwnership
- fixed tests according to new spec

### CODE REVIEW

**Comment by maraoz** [comment]
ACK, please merge this doc updates to your branch and I'll merge this
https://github.com/FundRequest/zeppelin-solidity/pull/1

Thanks!

**Comment by Qkyrie** [comment]
Docs have been updated, if that's what you meant

**Comment by maraoz** [comment]
Thanks!

**Comment by Qkyrie** [comment]
You're welcome!

**Pull request merged**
