### PR TITLE
WIP: Bounty with factory

### PR DESCRIPTION
**Pull request by makoto**
This contract has no knowledge of target contract. Also this contract allows researchers to create own copy of the target so very similar to how current contract works.

The downside is that each user has to manually create a factory contract (or provide a generator script) so that bounty contract can create the copy of the target as below.

```
contract Deployer {
  function deployContract() returns (address) {
    return new SecureTargetMock();
  }
}
```

This solution can be compiled without error, though also it gets `out of gas` error.

### CODE REVIEW

**Comment by maraoz** [comment]
I like this approach, but please:
- rebase branch
- write more tests
- write some documentation
- make factory contract set at Bounty constructor. Current approach has security problems (one can set some malicious factory contract)

**Comment by gleim** [comment]
Great work @makoto looking forward to utilizing this soon & frequently

**Comment by gleim** [comment]
Looks good - also, thanks for the README addition

**Comment by makoto** [comment]
@gleim @maraoz I had issue rebasing this branch so instead I created new branch merging the upstream https://github.com/OpenZeppelin/zeppelin-solidity/pull/43

**Pull request closed without merging**
