### PR TITLE
Make SafeMath a library

### PR DESCRIPTION
**Pull request by maraoz**
Implements idea from @izqui 's post https://blog.aragon.one/library-driven-development-in-solidity-2bebcaf88736
What do you guys think?

This changes modify the API, so next release should be minor, not patch

### CODE REVIEW

**Comment by izqui** [comment]
I think this is a great idea!

Just my two wei here, I personally like [this API](https://github.com/AragonOne/zeppelin-solidity/blob/master/contracts/SafeMathLib.sol#L3) better for the calls, instead of '.safeAdd', etc. I think seeing that a function will be called it could be easily implied that the code is going to execute the library. And I think the '.plus', etc are prettier and more expressive.

**Comment by izqui** [comment]
Also a quick question, what is the gas overhead for performing a `delegatecall` for every safe operation vs doing it internally?

**Comment by frangio** [comment]
We should put the discussion into context. Currently `SafeMath` is implemented as a contract which must be inherited from in order to use the safe operations. The proposed change is to make it a library.

Like @izqui says in his blog post, libraries aren't allowed to inherit, but they can use other libraries. This implies that `SafeMath` *has* to be a library if it is going to be used as part of another library. Since we want to encourage the use of safe math in general, including in the development of other libraries, making `SafeMath` itself a library seems necessary.

This has consequences for the API because library functions are used different from contract functions. They can be used in two different ways. The first one is as functions by prefixing them with the library name. (Assume `x`, `y` are of type `uint`.)
```
using SafeMath;
uint z = SafeMath.add(x, y);
```
The second one is attaching the functions as methods to a type.
```
using SafeMath for uint;
uint z = x.add(y);
```

Seeing the two examples above I'd be inclined to remove the `safe` prefix from the functions, since in the first case it's redundant. However it may not be explicit enough in the second case that `add` is a safe operation.

Regarding `add` vs `plus`, etc., I think I prefer the former.

I don't know about the gas gost of `delegatecall`. Wouldn't the solidity compiler be able to compile it away to a simple `call` anyway? Since they are pure functions.

**Comment by izqui** [comment]
I don't know why I though the gas cost was different, the last version of the yellowpaper seems to express that `C (σ, μ) if w=CALL ∨ CALLCODE ∨ DELEGATECALL` which I understand that the three have the same gas cost and which is 700 gas.

If confirmed, 700 gas for a delegatecall seems cheap to me a definitely not a deal breaker. Can anyone confirm?

Source: http://yellowpaper.io

**Comment by maraoz** [comment]
@izqui your analysis seems correct.
@frangio I implemented your proposed names.

If everyone agrees, I'm for merging this PR as is and turning SafeMath into a proper lib

**Pull request merged**
