### PR TITLE
Remove duplicated constructor call in FinalizableCrowdsaleImpl

### PR DESCRIPTION
**Pull request by federicobond**
This is going to be enforced by the compiler soon.

### CODE REVIEW

**Comment by Shrugs** [comment]
Can you give context for this?

**Comment by federicobond** [comment]
Yes! See [here](https://github.com/ethereum/solidity/pull/3305).

**Comment by frangio** [comment]
Thanks @federicobond. 🙂

I wouldn't see this as duplicated super constructor calls. I find it somewhat weird because of the Solidity inconsistency between zero-arity constructors, which are implicitly called, and non-zero-arity constructors, which aren't.

Regardless, I'm all for removing the redundant constructor call in this case.

Can you rebase before merging?

**Comment by federicobond** [comment]
Rebased. I agree with the inconsistency in zero-arity constructors. I'll bring it up for discussion in the Solidity repo.

**Comment by federicobond** [comment]
Rebased.

**Pull request merged**
