### PR TITLE
Make Stoppable a subclass of Ownable

### PR DESCRIPTION
**Pull request by federicobond**
It's always nice to remove lines of code :)

### CODE REVIEW

**Comment by AugustoL** [comment]
Cant function emergencyStop() on Stoppable contract use the modifier onlyOwner instead of checking the msg.sender inside the function?

**Comment by federicobond** [comment]
Right! Missed it when I made the changes.

**Comment by maraoz** [comment]
@federicobond maybe you'll have to change Ownable to throw instead of skip or some test will break

**Comment by federicobond** [comment]
All tests are green, which probably means coverage is insuficient.

I didn't want to change the behaviour of Ownable in the same pull request though.

**Comment by maraoz** [comment]
tested ACK

**Pull request merged**
