### PR TITLE
Solium run and Solium version update

### LINKED ISSUE #656: Merge solium PR and integrate into CI/testing
Merge #556 and add a `lint:sol` command to npm scripts. integrate into travis.

### PR DESCRIPTION
**Pull request by azavalla**
refs #75 and #555 
Fixes #656

Solium config:

- "custom-rules-filename" is deprecated.
- "no-with" rule is also deprecated.

- "double-quotes" rule is deprecated. It was replaced by ["quotes", "double"].

- Added "mixedcase" (is included in solium:all). As pointed out on #555, bugs with this rule where fixed. Is there another reason to not to use it?

- Added security plugin. Set severity for security rules appropriately.
https://github.com/duaraghav8/solium-plugin-security#list-of-rules

- These rules are included in ` solium:all`, so they where removed:
    imports-on-top
    variable-declarations
    array-declarations
    operator-whitespace
    lbrace
        camelcase
    uppercase
    no-empty-blocks
    no-unused-vars
    blank-lines
    indentation
    whitespace
    deprecated-suicide
    pragma-on-top

Other:
	Refactored contracts to comply with the new rules.
	Abstract base contracts constructors marked internal instead of public.

Issues:
"quotes" rule doesn't seem to be working.

### CODE REVIEW

**Comment by duaraghav8** [comment]
Thanks for making the PR @azavalla! 

(Just for general information)
CI builds can fail because of Solium. This happens when you specify a particular lint rule as `error` and that rule flags some code. A solium `error` always results in exit code > 0. You could set the rule to `warning` to avoid build fails but still be notified of the lint errors.

**Comment by azavalla** [comment]
Thanks for the heads-up @duaraghav8! Any ideas on the "quotes" rule issue?

**Comment by duaraghav8** [comment]
@azavalla I don't follow. Can you point me to which quotes-related issue you're talking about?

**Comment by azavalla** [comment]
@duaraghav8 there are both single and double quoted string literals, but Solium doesn't seem to catch them.

**Comment by duaraghav8** [comment]
ah yes that's a limitation of the lint rule currently, sorry about that. We'll be fixing it in a subsequent release but as of now it only flags strings.

**Pull request closed without merging**
