### PR TITLE
Basic will contract

### PR DESCRIPTION
**Pull request by JGcarv**
Created a basic Will contract, in response to issue #134 .

It's very basic still, with a lots of room for additions and improvements(eg: distributing funds unequally among heirs or also leaving some kind of message).

The tests covers all contracts functions, but aren't the most elegantly written(I'll sure work on that later, but it's a start).

If you have any questions, let me know!

### CODE REVIEW

**Comment by federicobond** [comment]
Hi @JGcarv, thank you for your contribution! It's an interesting and useful contract indeed. I think we may get some extra mileage from it by separating the ping/health-check behaviour from the particulars of the inheritance scheme. Not all wills will want to split evenly among heirs, and some wont even have many heirs, or may want to add additional conditions to claimers. We should remain open to all these possibilities when designing OpenZeppelin contracts.

In my opinion, we should involve using at least 3 contracts: one is your persistent identity, another your health-check and a third one that will represent your actual will. The health check will unlock some methods if not pinged within a certain timeframe, these methods can then call the persistent identity to extract or perform transactions delivering funds to your inheritance scheme, which will then handle the details of distributing your inheritance across people and time.

Would love to hear your feedback on this.

**Comment by JGcarv** [comment]
Thank's for you response, @federicobond! Really interesting ideas, I'll definitely try to implement this.

I'm not sure if I fully understand the difference between an identity contract and the proper will contract, though. Is the identity a kind of "super wallet", where you not only hold funds, but also declare who should keep your tokens if something happens to you and the Will is the contract that handles this distribution?

**Comment by federicobond** [comment]
Your persistent identity is indeed a kind of "super wallet". Access to your identity can be authorized to different devices (see ConsenSys' [uport](https://www.uport.me/) for an example) and your health-check contract can call some methods too to execute you will, but will only do so if it hasn't received any pings during a certain amount of time.

A third contract, your will, will probably be the recipient of all your funds and will enable others to extract them according to different rules.

**Comment by JGcarv** [comment]
Hmm I see. I'll take a time to study what uPort really does(and how it does it) and then get back to this issue.

**Comment by JGcarv** [comment]
Hello @federicobond. I was working in the Will scheme and before going any further I would like to share my current contracts, which are not fully implemented yet, but I guess it's enough to understand the general workings. 

I think it's a smart decision to separate the HealthCheck from the Will, but I'm a bit unsure about the practicality of an Identity contract, in this case. I went through uport's design and it's fantastic, but I believe most of its value holds on the proxy + controller contracts.  

I would like to hear your thoughts on the current state, on what could be improved, etc. Thanks in advance!

```
pragma solidity ^0.4.9;
import "./ownable.sol";


contract Identity is Ownable{
    
    address healthCheck;
    address will;
    
    modifier onlyInactive(){
        HealthCheck hc = HealthCheck(healthCheck);
        if (hc.checkStatus()) throw;
        _;
    }

    function deposit() payable returns(uint) {
        return this.balance;
    }
    
    function transfer(address to, uint amount){
        to.transfer(amount);
    }
    
    function pingHealth(){
        HealthCheck hc = HealthCheck(healthCheck);
        hc.ping();
    }
    
    function releaseWill() onlyInactive {}
    
    function changeWillAddress(){}
    
    
}


contract Will {
    
    address identity;
    uint version;
    bool locked;
    mapping(address => Beneficiary) heirs;
    
    struct Beneficiary {
        bytes32 name;
        uint weight;
        uint portions;
        uint timeInterval;
    }
    
    modifier onlyOwner(){
        if(msg.sender != identity) throw;
        _;
    }
    
    modifier onlyUnlocked(){
        if(locked) throw ;
        _;
    }
    
    function Will(){}
    
    function recieveFunds() payable {}
    
    function addBeneficiary(address addr, bytes32 name, uint weight, uint portions, uint timeInterval) onlyOwner{}
    
    function removeBeneficiary(address addr) onlyOwner {}
    
    function claim() onlyUnlocked{}
}


contract HealthCheck{
    
    address identity;
    bool public active;
    
    uint public lastPing;
    uint public PingInterval;
    
    modifier onlyOwner(){
        if(msg.sender != identity) throw;
        _;
    }
    
    function ping(){
        lastPing = now;
    }
    
    function changeInterval(){}
    
    function checkStatus() constant returns(bool checked){
        return active;
    }

}
```

**Comment by GNSPS** [comment]
Hey @federicobond, really cool stuff!

Although I do find this pinging mechanism a bit inefficient. What if you made it so that the owner only had to ping when someone claimed their "death"?

Worst case scenario you have to ping as many times as in the above but it could also save you from wasting a lot of fees from extensive pinging.

**Comment by federicobond** [comment]
@GNSPS that's a good idea. We could also make it so that the person who wants to claim death must deposit a certain amount of value, to further prevent spam. If the person is alive, they can just claim the value deposited, but the original claimer can recover it if the health-check timeframe expires and the will is executed.

**Comment by federicobond** [comment]
I'll take a look at it next week @JGcarv. Very busy right now.

**Comment by JGcarv** [comment]
Solid idea @GNSPS, makes it way easier for the user. And no problem @federicobond, take your time!

**Comment by JGcarv** [comment]
Hey @federicobond. I got back to this issue today and looking at it now I feel that it got a bit too complex for OZ( I know there's the crowdsale scheme, which is quite complex as well, but it is way more 'reusable'). Maybe a way is to separate the 'Identity' contract and make it more generic to fit other issues, making it a way simpler uPort. 
Anyway, just wanted to hear from you before going forward.

**Comment by JGcarv** [comment]
I guess this is a bit outdated now, so I'll close it.

**Comment by Shrugs** [comment]
@JGcarv I like this idea, and now that SplitPayment has landed in 1.4.0, it might make sense to use that for the uneven will feature.

**Pull request closed without merging**
