### PR TITLE
Small SafeMath.sol gas improvements (add & mul).

### PR DESCRIPTION
**Pull request by DeltaBalances**
# 🚀 Description
Some small changes to `SafeMath.sol` that reduce gas usage, comparable to #811.

This simply moves the variable definition `uint256 c` to the return value `returns (uint256)`.
Applicable to both `add(...)` and `mul(...)`.
```
//before
function add(uint256 a, uint256 b) internal pure returns (uint256) {
    uint256 c = a + b;
    ...
}
//after
function add(uint256 a, uint256 b) internal pure returns (uint256 c) {
    c = a + b;
    ...
}
```

## Gas usage
Gas execution costs in Remix (optimizer enabled, 0.4.21+commit.dfe3193c) 
V1 is the current SafeMath, V2 is the proposed change.

|function|Input|execution cost| 
|---|---|---|
|`mulV1(,)`|`(2,5)`|341 gas|
|`mulV2(,)`|`(2,5)`|331 gas|
| | | |
|`mulV1(,)`|`(0,1)`|284 gas|
|`mulV2(,)`|`(0,1)`|280 gas|
| | | |
|`addV1(,)`|`(1,1)`|274 gas|
|`addV2(,)`|`(1,1)`|269 gas|

(2 different inputs for `mul` as it has early termination on `a = 0`)

Testing functions:
```
pragma solidity ^0.4.18;

/* Original multiplication */
library SafeMath1 {
    function mul(uint256 a, uint256 b) internal pure returns (uint256) {
        if (a == 0) {
            return 0;
        }
        uint256 c = a * b;
        assert(c / a == b);
        return c;
   }
}

/* Improved multiplication */
library SafeMath2 {
    function mul2(uint256 a, uint256 b) internal pure returns (uint256 c) {
        if (a == 0) {
            return 0;
        }
        c = a * b;
        assert(c / a == b);
        return c;
    }
}

/* Original addition */
library SafeMath3 {
    function add(uint256 a, uint256 b) internal pure returns (uint256) {
        uint256 c = a + b;
        assert(c >= a);
        return c;
    }
}

/* Improved addition */
library SafeMath4 {
     function add2(uint256 a, uint256 b) internal pure returns (uint256 c) {
        c = a + b;
        assert(c >= a);
        return c;
    }
}

/* Test contracts with functions to call mul && add */

contract UsingSafeMath {
    function mulV1(uint256 a, uint256 b) public pure returns (uint256) {
        return SafeMath1.mul(a,b);
    }
}
contract UsingSafeMath2 {
    function mulV2(uint256 a, uint256 b) public pure returns (uint256) {
        return SafeMath2.mul2(a,b);
    }
}
contract UsingSafeMath3 {
    function addV1(uint256 a, uint256 b) public pure returns (uint256) {
        return SafeMath3.add(a,b);
    }
}
contract UsingSafeMath4 {
    function addV2(uint256 a, uint256 b) public pure returns (uint256) {
        return SafeMath4.add2(a,b);
    }
}
```

---

- [x] 📘 I've reviewed the [OpenZeppelin Contributor Guidelines](/docs/CONTRIBUTING.md)
- [x] ✅ I've added tests where applicable to test my new functionality.
- [x] 📖 I've made sure that my contracts are well-documented.
- [x] 🎨 I've linted  `SafeMath.sol` with Solium

### CODE REVIEW

**Comment by k06a** [comment]
You can also remove `return c;` lines.

**Comment by DeltaBalances** [comment]
Removing `return c;` in `add()` actually increases the gas usage from 269 to 273.
Personally I prefer to keep either `return c;` or `// return c;` for readability.

**Comment by k06a** [comment]
@DeltaBalances ha-ha, thanks!

**Comment by DeltaBalances** [comment]
I checked it again on 0.4.22+commit.4cb486ee, and the gas difference remain the same.


I updated the fork by rebasing master as suggested [here](https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/CONTRIBUTING.md)
> Please use rebase instead of merge when updating your fork.

But that seems to have messed with the review process, apologies for that.

**Comment by frangio** [comment]
Thanks!

**Pull request merged**
