### PR TITLE
Non Tradable ERC20 Token

### PR DESCRIPTION
**Pull request by jchittoda**
Added NonTradableToken.sol
Non tradable ERC20 tokens, those are non transferable tokens.
Why is this required ?
- When a company ABC goes to private investors before even presale/ICO. Company wants to collect ETH using the Mintable Smart Contract, but company do not wants to make these tokens tradable.
- When ABC company launch their main ICO, then company will pre-fill the tokens for the private investors in main ICO Smart Contract.

### CODE REVIEW

**Comment by adklempner** [comment]
I believe this can be implemented using [LimitedTransferToken](https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/token/LimitedTransferToken.sol) as a base

**Comment by jchittoda** [comment]
@adklempner If contract creator uses  has LimitedTransferToken as a base then he has to do the following to make it Non Tradable
- Override transferableTokens() method

**Comment by SylTi** [comment]
What's the point of using the ERC20 standard for a token that is not tradeable?  Just create a contract that's doesn't have transfer functions

**Comment by jchittoda** [comment]
When a company looking from some private investors to invest in the ICO even before the actual ICO. In that case company would not want the private investors to trade the tokens they minted by giving ETHs.

**Comment by SylTi** [comment]
You can do that with a PausableToken

**Comment by jchittoda** [comment]
With PausableToken, I see a security issue.
What if the owner's private key is compromised in future. In that case hacker will be able to UnPause the tokens anytime.

We must create a contract full proof that no possibility of hacking is there.

**Comment by reiven** [comment]
> What if the owner's private key is compromised in future

Thats why you use a multisig address for ownership

**Comment by SylTi** [comment]
Or a hardware wallet.
But I will ask again, if you can't unpause the transfer at some point. Why would you need functions used for transfer?

You could also put the tokens for the pre-investor inside a TokenTimeLock

**Comment by jchittoda** [comment]
> Thats why you use a multisig address for ownership
@reiven Can we make a multisig wallet the owner of a contract called PausableToken ?

**Comment by jchittoda** [comment]
@SylTi When I will create my token related contract I will use the ERC20.sol and import it.
Are you suggesting that I should not import those files as it is and make changes into those files and remove the transfer() function ?

**Comment by reiven** [comment]
@jchittoda sure! you can make a multisig address owner of any contract

**Comment by SylTi** [comment]
What I'm saying is, this pull request, in my opinion, is not useful. It's essentially the same thing as PausableToken without the possibility to turn it on.  And inheriting from an ERC20 token to disable everything is a bad approach, if you don't want the functions, just don't inherit from it. 

If you want help with your own code, this is not the place. You can join us on the slack channel we will be happy to help.

**Comment by ajsantander** [comment]
Agree with @SylTi and with others.

**Comment by dbrowne24** [comment]
@jchittoda This is actually quite useful for creating a Dapp similar to Steemit, where the developers create 2 tokens. One transferable token that can be exchanged for bitcoin / eth / or whatever. And one to be used to define a users reputation. The reputation should be able to be converted to the tradable token and vice versa.
You don't want users to be able to transfer the reputation tokens because they could perform an action that requires reputation, then transfer the tokens to another address and perform the address again. But a timelock could prevent that.

**Pull request closed without merging**
