### PR TITLE
Feature: Ability to use crowdsale contract with pre minted tokens

### LINKED ISSUE #351: Decouple Crowdsale from MintableToken
(Extracted verbatim from #310 by @jakub-wojciechowski.)

Crowdsale contract is tightly coupled to MintableToken. Wouldn’t it be better to make the base Crowdsale as generic as possible? It will allow others to implement a model when the token pool is created before a sale and then transferred rather than minted. Currently, it’s impossible to override methods like:

```
function createTokenContract() internal returns (MintableToken) {
```

I will suggest extracting:

```
token.mint(beneficiary, tokens);
```

to

```
function distribute(beneficiary, tokens) internal {
  token.mint(beneficiary, tokens); 
}
```

And probably rename:

```
function createTokenContract() => setupTokenContract()
```

### PR DESCRIPTION
**Pull request by MADANA-HQ**
Legal issues and perhaps other reasons such as pre sales require the need to use the crowdsale contract with already minted tokens. Currently the zeppelin-solidity repo does not offer a solution for this problem. I have developed a small contract which can be assigned tokens with the StandardTokens approve function and therefore gains pseudo minting abilities. This contract can be passed on to the Crowdsale contract, allowing it to sell the already minted tokens.
Because of the various important steps needed to be done outside of the crowdsale contract, I opted to create an example including a vault contract in which the that outside logic is shown.
Further I created a Mintable interface, which replaces the MintableToken inside the Crowdsale contract. This is not necessary and possibly creates backwards compatibility issues, however I chose to add an interface for better code structure and to prevent misconception. 

Fixes #351.

### CODE REVIEW

**Comment by frangio** [comment]
Actually the `Mintable` interface is a great idea! There have been several approaches to this problem before and this idea ha never come up (see #528 for example) but it's obvious now that it should be this way.

We're making a release today so I can't look at it in detail no but we'll do it soon.

Thanks @MADANA-HQ!

**Comment by lead4good** [comment]
@Shrugs As far as I understand, the CompositeCrowdsale does not solve this issue. I believe though that they would fit together by combining the CompositeCrowdsale with a DistributionStrategy which then pseudo mints tokens via the PseudoMinter contract.

**Comment by lead4good** [comment]
@frangio I've updated this PR to include the changes form #690.

**Comment by lead4good** [comment]
@frangio Since #690 implemented a breaking change, I'd suggest to merge this PR quickly since it implements another breaking change at the same location, changing the MintableToken in the Crowdsale constructor to the Mintable interface.

**Comment by ajsantander** [comment]
@MADANA-HQ 
Thanks for your suggestion. We've taken your idea and incorporated it in a general refactor of crowdsales.
If you're interested in following progress, please see #744.

**Pull request closed without merging**
