### PR TITLE
Added internal keyword to PRICE variable

### PR DESCRIPTION
**Pull request by RFVenter**
Added internal keyword to PRICE variable to enabled inherited Contracts to set the price later within inherited Contracts.

### CODE REVIEW

**Comment by maraoz** [comment]
From the solidity docs: `For state variables, external is not possible and the default is internal.`
source: https://solidity.readthedocs.io/en/develop/contracts.html

So this wouldn't change anything right?

**Comment by federicobond** [comment]
*Note:* non-constant state variables should be in mixedCase, not UPPERCASE.

**Comment by RFVenter** [comment]
I agree with setting this ti public instead of private. Solidity will then auto create a getter function. I have removed the getPrice function completly.

**Comment by maraoz** [comment]
The idea of having a price function is that most people would want to change it into some other behavior. That's why the comment said: ` // replace this with any other price function`

**Comment by RFVenter** [comment]
Isn't Crowdsale.sol a base Contract meant to be inherited from?

**Comment by maraoz** [comment]
Exactly. And if you remove `getPrice()`, inheriting contracts can't change that behavior

**Comment by RFVenter** [comment]
According to solidity spec, an automatic getter function is generated for all public state variables, making getPrice() redundant. Even if it is left as is, why does the createTokens function have to call the getPrice function instead of simply accessing the PRICE variable directly?

**Comment by maraoz** [comment]
It's for an educational purpose. Most real-life tokens implement a price function that depends on time. Making it a function (even though it only returns a constant value) makes it easier for devs to understand the potential of writing your own price function. Closing this

**Comment by RFVenter** [comment]
OK?

**Pull request closed without merging**
