### PR TITLE
Optimized ERC20 implementation by removing extra checks

### LINKED ISSUE #816: Optimize ERC20 implementation
## 🎉 Description

Some of ERC20 implementation methods contain multiple checks of the same issues

- [ ] 🐛 This is a bug report.
- [x] 📈 This is a feature request.

## 📝 Details

The problem is increased gas usage for no reason.

## 🔢 Code To Reproduce Issue

For example:
```
function transfer(address _to, uint256 _value) public returns (bool) {
    require(_to != address(0));
    require(_value <= balances[msg.sender]);

    // SafeMath.sub will throw if there is not enough balance.
    balances[msg.sender] = balances[msg.sender].sub(_value);
    balances[_to] = balances[_to].add(_value);
    Transfer(msg.sender, _to, _value);
    return true;
}
```

Why do we need second `require` if we already have `SafeMath.sub`. Do we really need to handle `uint256` overflow with `SafeMath.add`?

Same for this:
```
function transferFrom(address _from, address _to, uint256 _value) public returns (bool) {
    require(_to != address(0));
    require(_value <= balances[_from]);
    require(_value <= allowed[_from][msg.sender]);

    balances[_from] = balances[_from].sub(_value);
    balances[_to] = balances[_to].add(_value);
    allowed[_from][msg.sender] = allowed[_from][msg.sender].sub(_value);
    Transfer(_from, _to, _value);
    return true;
}
```

I think we can easily remove second and third `require`s, because both `SafeMath` calls handle exactly the same cases.

### PR DESCRIPTION
**Pull request by k06a**
Fixes #816

# 🚀 Description

Removed unnecessary SafeMath checks after `require`s from ERC20 implementation

- [x] 📘 I've reviewed the [OpenZeppelin Contributor Guidelines](/docs/CONTRIBUTING.md)
- [x] ✅ I've added tests where applicable to test my new functionality.
- [x] 📖 I've made sure that my contracts are well-documented.
- [ ] 🎨 I've run the JS/Solidity linters and fixed any issues (`npm run lint:all:fix`).

### CODE REVIEW

**Comment by DanielMReed** [comment]
Is the gas cost of this noted anywhere? It says it saves gas but by how much? Is it certain that the safeMath checks do not provide extra beenfit?

**Comment by k06a** [comment]
@DanielMReed successed tests on CI mean no benefits of removed SafeMath calls.

**Comment by k06a** [comment]
@DanielMReed not many gas will be saved on single tx, but a lot of on bunch of transactions. Anyway I wanna understand why to have double checks.

**Comment by DanielMReed** [comment]
@k06a If you check the log of the StandardToken, the .sub() was there to start, then the prechecks added, then no removal of the .sub() it seems. So this may be a valid step

**Comment by facuspagnuolo** [comment]
We prefer keep safemath operations even for those obvious scenarios. This is just to avoid confusion and to ensure such arithmetic won't cause a problem due to an overflow.

**Comment by k06a** [comment]
@facuspagnuolo, why to keep `require`s?

**Comment by DanielRX** [comment]
I have to agree with @k06a here @facuspagnuolo 

You have

`require(x<y);`
`y.sub(x);` which then does `assert(x<y);`

One of those checks is redundant, and therefore added extra cycles to the code

**Comment by facuspagnuolo** [comment]
@k06a that `require` is strictly related to the domain problem, a token transfer in this case. It would be weird not to have a precondition ensuring you won't send more than you have. The fact SafeMath's overflow check also covers that validation is a coincidence, and I prefer being redundant to avoid confusion.

**Pull request closed without merging**
