### PR TITLE
Create CappedToken, a capped MintableToken

### PR DESCRIPTION
**Pull request by cwhinfrey**
This PR implements CappedToken, a capped MintableToken. This token will allow tokens to be minted up until the cap is reached.

### CODE REVIEW

**Comment by Qqwy** [comment]
What would the advantage of this be over using the `CappedCrowdsale` contract?

**Comment by cwhinfrey** [comment]
@Qqwy The CappedCrowdsale sets a cap on the amount of funds raised, not on the number of tokens. A token sale may have a rate that adjusts over time and want to set the cap of the sale by the number of tokens not the amount of funds raised.

**Comment by cwhinfrey** [comment]
@Qqwy This could also be used in conjunction with CappedCrowdsale. One example of this would be if a crowdsale distributed tokens to contributors up to a set funding amount and then any additional tokens would be minted for an airdrop up to a set token cap.

**Comment by ajsantander** [comment]
Looks great. 

One small thing tho: 
Can you change L28 to `return super.mint(_to, _amount);`? (use super)

See http://solidity.readthedocs.io/en/develop/contracts.html#inheritance
Directly calling a method on of the members of the inheritance chain can cause undesired results (i.e. skipping parts of the chain), and even though it wouldn't particularly hurt in this case, we want to encourage the use of super as best practice.

**Comment by cwhinfrey** [comment]
@ajsantander Thanks for taking a look. :) Good to know. Just fixed it.

**Comment by frangio** [comment]
Thanks @cwhinfrey! I added an extra commit (https://github.com/OpenZeppelin/zeppelin-solidity/commit/12303ceaf54293b97e8925c0c735a9a81d834a8d) fixing the comparison of bignumbers. See #204.

**Pull request merged**
