### PR TITLE
improve mul performance and reduce gas cost

### PR DESCRIPTION
**Pull request by emn178**

### CODE REVIEW

**Comment by greggy** [comment]
Maybe you should check if b is equal 0 too?

**Comment by cannabhakt** [comment]
greggy raises a good point; if "b" were zero the code wouldn't pick it up

**Comment by emn178** [comment]
If most cases were both non-zero, check b will increase gas cost more than original version.
If only check a, it should be better than original version at least.

**Comment by spalladino** [comment]
> If only check a, it should be better than original version at least.
@emn178 could you provide some tests on actual gas usage? I'm not sure if the extra gas consumed by adding a branching on every multiplication will bye compensated by the gain on the zero case.

**Comment by emn178** [comment]
I use this to test
https://ethereum.github.io/browser-solidity/#version=soljson-v0.4.18+commit.9cf6e910.js

Original:


After change:

**Comment by spalladino** [comment]
Merged then, thanks @emn178!

**Comment by destenson** [comment]
Gas consumption can be improved at least an additional ~50% by eliminating the divide.

The current implementation uses 335 gas compiled with optimizations on with [Remix](https://remix.ethereum.org/#optimize=true&version=soljson-v0.4.25+commit.59dbf8f1.js):
```
  function mul(uint256 a, uint256 b) public pure returns (uint256) {
    // Gas optimization: this is cheaper than requiring 'a' not being zero, but the
    // benefit is lost if 'b' is also tested.
    // See: https://github.com/OpenZeppelin/openzeppelin-solidity/pull/522
    if (a == 0) {
      return 0;
    }

    uint256 c = a * b;
    require(c / a == b);

    return c;
  }
```

The following version uses 221 gas compiled with the same:
```
  function mul(uint a, uint b) public pure returns(uint c) {
    c = uint(int(a) * int(b));
    require(c >= a);
  }
```

**Comment by devilstock** [comment]
How to verified and publish Token TRC-21. Who know help me? Thank you

**Comment by stefek99** [comment]
I notice difference of `1 gas`: https://github.com/OpenZeppelin/openzeppelin-contracts/pull/522#issuecomment-344159199

Based on `transaction cost` and `execution cost`

**Comment by uygarali** [comment]
bu sözleşmede slippage gas değerini nasıl yükseltebiliriz? yüzde 1 gibi sanırım yüzde 5 yapmak istiyorum

**Comment by uygarali** [comment]
How can we increase the slippage gas value in this contract? Like 1 percent I think I want to make it 5 percent

**Comment by Nikolay1989m** [comment]
Greetings! how to check the source code of the contract and verify the ownership of the contract ???

**Comment by spalladino** [comment]
@Nikolay1989m please search in the [forum](https://forum.openzeppelin.com/), there is a guide about verifying source code. Do not use github issues for support questions. Thanks!

**Comment by Juman88** [comment]
- [ ] Hi this belongs to me erc account is juman88 and I really need help getting my funds it's been a long while. I will admit I do not know what I'm doing

**Review by Juman88 — COMMENTED** [review]
This belong to me

**Pull request merged**
