### PR TITLE
Feature - Token wallet

### PR DESCRIPTION
**Pull request by JGcarv**
Simple base contract that allows child contracts to handle tokens. 

It can be used for contracts that expect to receive any token(wallets, vaults, exchanges, etc) and as a safe measure to avoid locking tokens in a unprepared contract.

### CODE REVIEW

**Comment by frangio** [comment]
This is a pretty cool idea @JGcarv!

What was the rationale for adding the `tokenName` functions?

**Comment by JGcarv** [comment]
I added the name feature because at the time I was thinking of a more user
facing application, and therefore, using names is more friendly than
addresses. But, it's definitely not necessary.

Another thing, I also intended to make it ERC223 compatible, but that's
still is a ongoing discussion, so I decided to leave it for now.

**Comment by frangio** [comment]
Yeah, I think the user- friendly names should be resolved elsewhere, e.g. by using [ENS](http://ens.domains) or at the application level.

**Comment by JGcarv** [comment]
Agreed! Just removed the functions that used `tokenName` and rebased the branch.

**Pull request closed without merging**
