### PR TITLE
Update ERC827.sol to not use function overloading

### PR DESCRIPTION
**Pull request by elie222**
# 🚀 Description

Renaming of ERC827 function names to avoid using function overloading. This also needs to be accepted by Ethereum team.

This causes problems with projects such as Vyper:
https://github.com/ethereum/vyper/issues/738

- [x] 📘 I've reviewed the [OpenZeppelin Contributor Guidelines](../blob/master/CONTRIBUTING.md)
- [x] ✅ I've added tests where applicable to test my new functionality.
- [x] 📖 I've made sure that my contracts are well-documented.
- [x] 🎨 I've run the JS/Solidity linters and fixed any issues (`npm run lint:all:fix`).

### CODE REVIEW

**Comment by AugustoL** [comment]
@elie222 can you make the changes in the tests to run with the new method names?

**Comment by elie222** [comment]
Yes. I will do this

**Comment by elie222** [comment]
I updated the tests and they're all passing now.

**Comment by AugustoL** [comment]
@elie222 They are not passing in travis, https://travis-ci.org/OpenZeppelin/zeppelin-solidity/jobs/362430479#L3538

**Comment by elie222** [comment]
Yup. Sorry. Missed running some tests locally. Should work on Travis now

**Comment by AugustoL** [comment]
@elie222 great, with the new functions names the `findMethod` function in ERC827Token tests wont be needed, can you remove it too, it will make tests more readable?

**Comment by elie222** [comment]
Yes makes sense. Will try and get around to it tomorrow.

**Comment by k06a** [comment]
Maybe to keep both method names?

**Comment by elie222** [comment]
If we're against this because it's considered "dangerous", then would be
best not to? It's early enough in the life of erc827 that we can still
remove the previous names?

**Comment by AugustoL** [comment]
is early enough, we dont want want duplicated code, I think we should keep the new names that avoid overloading.

**Comment by k06a** [comment]
@AugustoL no need to duplicate code, `approve(address,uint256,bytes)` can just call `approveAndCall(address,uint256,bytes)`

**Comment by elie222** [comment]
Removed `findMethod`. Tests and linter passing

**Comment by AugustoL** [comment]
@elie222 can you fix the conflicts in ERC827.sol so I can merge it?

**Pull request merged**
